application: shouldalexrun
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/favicon\.ico
  static_files: /images/favicon.ico
  upload: /images/favicon\.ico

- url: /templates/data\.txt
  static_files: /templates/data\.txt
  upload: /templates/data\.txt

- url: /\.gitignore
  static_files: /\.gitignore
  upload: /\.gitignore

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /css
  static_dir: css

- url: /templates
  static_dir: html

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
